#!/usr/bin/env bash
#	SPDX-License-Identifier: MPL-2.0
#	mksite.sh
#
#	Generate C API man-pages, convert them to HTML format and then generate
#	an index page.
#
#	Copyright (c) 2024 Yao Zi.

warn() {
	echo "$@" >&2
}

die() {
	warn "$@"
	exit 1
}

usage() {
	echo "mksite.sh <OUR_FORMAT_DOC> <OUTPUT_DIR>"
}

ofdoc="$1"
outdir="$2"
mkman="$(dirname $0)/mkman.lua"

[ "$outdir" ] && [ "$ofdoc" ] || usage
[ -f "$mkman" ] || die "$mkman doesn't exist"

man="$(which man)"
[ "$man" ] || die "Command man is required"

mkdir -p "$outdir"/{man,html}

"$mkman" "$ofdoc" "$outdir"/man || die "failed to generate manpages"

cat <<EOF > "$outdir"/html/index.html
<html>
<head> <title>Lua C API - Manpages</title> </head>
<body>
<h1>Lua C API</h1>
<p>Generated by
<a href="https://github.com/ziyao233/lua-manpage">lua-manpage</a></p>
<ul>
EOF

q='"'
for f in "$outdir"/man/*; do
	apiname="$(basename $f | cut -d '.' -f 1)"
	echo "<li><a href="$q"$apiname.html"$q">$apiname</a></li>" >> \
		"$outdir"/html/index.html
	mandoc -Thtml $f > "$outdir/html/$apiname.html"
done

cat <<EOF >> "$outdir"/html/index.html
</ul>
</body>
</html>
EOF
